<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>comet</string>
	</array>
	<key>name</key>
	<string>Comet</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>symbols</string>
			<key>match</key>
			<string>:[a-zA-Z_][a-zA-Z_0-9]*</string>
			<key>name</key>
			<string>constant.other.symbol.comet</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.function.comet</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>arguments</string>
			<key>match</key>
			<string>\\([a-zA-Z_][a-zA-Z_0-9]*)</string>
			<key>name</key>
			<string>keyword.source.comet</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>ordinary identifiers</string>
			<key>match</key>
			<string>[a-z][A-Z_][a-zA-Z_0-9]*</string>
			<key>name</key>
			<string>source.concord</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>numbers</string>
			<key>match</key>
			<string>\b[0-9]+(\.[0-9]*)?</string>
			<key>name</key>
			<string>constant.numeric.comet</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>strings</string>
			<key>match</key>
			<string>".*?[^\\]"</string>
			<key>name</key>
			<string>string.quoted.double.comet</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>operators and special characters</string>
			<key>match</key>
			<string>[+\-*/=&lt;&gt;\^&amp;|?!@]+</string>
			<key>name</key>
			<string>keyword.source.comet</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>comments</string>
			<key>match</key>
			<string>~.*</string>
			<key>name</key>
			<string>comment.source.comet</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.comet</string>
	<key>uuid</key>
	<string>451da72e-5710-4881-9dc8-757dc3ece19d</string>
</dict>
</plist>
